[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/informations-pratiques/urbanisme/consultations-concertations-et-enquetes-publiques-en-cours/"
to = "/informations-pratiques/consultations-concertations-et-enquetes-publiques-en-cours/"
status = 301

[[redirects]]
from = "/organisations/categories/mairies/"
to = "/mairies/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/tous-les-programmes-immobiliers-neufs/"
to = "/informations-pratiques/tous-les-programmes-immobiliers-neufs/"
status = 301

[[redirects]]
from = "/projets-urbains/les-projets-immobiliers-pres-de-chez-vous-rennes/"
to = "/informations-pratiques/les-projets-immobiliers-pres-de-chez-vous-rennes/"
status = 301

[[redirects]]
from = "/urbanisme/realiser-des-travaux-sur-le-domaine-public/"
to = "/informations-pratiques/realiser-des-travaux-sur-le-domaine-public/"
status = 301

[[redirects]]
from = "/equipe/estelle-soleillant/"
to = "/estelle-soleillant/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/realiser-des-travaux-sur-le-domaine-public/"
to = "/informations-pratiques/realiser-des-travaux-sur-le-domaine-public/"
status = 301

[[redirects]]
from = "/organisations/"
to = "/"
status = 301

[[redirects]]
from = "/urbanisme/droits-de-preemption/"
to = "/informations-pratiques/droits-de-preemption/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/les-demarches-dassainissement/"
to = "/informations-pratiques/les-demarches-dassainissement/"
status = 301

[[redirects]]
from = "/agenda/quartiers/rennes-centre-thabor-st-helier-a-guerin-baud-chardonnet/"
to = "/quartiers/rennes-centre-thabor-st-helier-a-guerin-baud-chardonnet/"
status = 301

[[redirects]]
from = "/actualites/famille-2/"
to = "/famille-2/"
status = 301

[[redirects]]
from = "/urbanisme/les-demarches-dassainissement/"
to = "/informations-pratiques/les-demarches-dassainissement/"
status = 301

[[redirects]]
from = "/mairie-de-bourgbarre/"
to = "/"
status = 301

[[redirects]]
from = "/organisations/ecole-maternelle-oscar-leroux/"
to = "/"
status = 301

[[redirects]]
from = "/se-loger/ecowatt-pour-veiller-sur-sa-consommation-electrique/"
to = "/informations-pratiques/ecowatt-pour-veiller-sur-sa-consommation-electrique/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/logements-degrades/"
to = "/informations-pratiques/logements-degrades/"
status = 301

[[redirects]]
from = "/categories/social-sante/"
to = "/social-sante/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/patrimoine-des-centres-anciens/"
to = "/informations-pratiques/patrimoine-des-centres-anciens/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/demander-un-logement-hlm/"
to = "/informations-pratiques/demander-un-logement-hlm/"
status = 301

[[redirects]]
from = "/informations-pratiques/projets-urbains/les-projets-immobiliers-pres-de-chez-vous-rennes/"
to = "/informations-pratiques/les-projets-immobiliers-pres-de-chez-vous-rennes/"
status = 301

[[redirects]]
from = "/actualites/famille-1/"
to = "/famille-1/"
status = 301

[[redirects]]
from = "/organisations/centre-local-d-information-et-de-coordination-clic-noroit/"
to = "/"
status = 301

[[redirects]]
from = "/se-loger/ecotravo-vous-aide-a-renover-votre-logement/"
to = "/informations-pratiques/ecotravo-vous-aide-a-renover-votre-logement/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/les-aides-a-lachat-dun-logement/"
to = "/informations-pratiques/les-aides-a-lachat-dun-logement/"
status = 301

[[redirects]]
from = "/projets/"
to = "/"
status = 301

[[redirects]]
from = "/centre-local-d-information-et-de-coordination-clic-noroit/"
to = "/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/logement-pour-les-jeunes-et-les-etudiants/"
to = "/informations-pratiques/logement-pour-les-jeunes-et-les-etudiants/"
status = 301

[[redirects]]
from = "/se-loger/demander-un-logement-hlm/"
to = "/informations-pratiques/demander-un-logement-hlm/"
status = 301

[[redirects]]
from = "/urbanisme/consultations-concertations-et-enquetes-publiques-en-cours/"
to = "/informations-pratiques/consultations-concertations-et-enquetes-publiques-en-cours/"
status = 301

[[redirects]]
from = "/urbanisme/les-procedures-participatives-obligatoires-archivees/"
to = "/informations-pratiques/les-procedures-participatives-obligatoires-archivees/"
status = 301

[[redirects]]
from = "/urbanisme/consulter-les-documents-du-plui/"
to = "/informations-pratiques/consulter-les-documents-du-plui/"
status = 301

[[redirects]]
from = "/equipe/matthieu-delsaut/"
to = "/matthieu-delsaut/"
status = 301

[[redirects]]
from = "/equipe/guillaume-rouan/"
to = "/guillaume-rouan/"
status = 301

[[redirects]]
from = "/se-loger/se-loger-a-rennes-quand-on-vieillit/"
to = "/informations-pratiques/se-loger-a-rennes-quand-on-vieillit/"
status = 301

[[redirects]]
from = "/actualites/2024-12-03-test/"
to = "/2024-12-03-test/"
status = 301

[[redirects]]
from = "/projets-urbains/nouvelles-fabriques-de-la-ville/"
to = "/informations-pratiques/nouvelles-fabriques-de-la-ville/"
status = 301

[[redirects]]
from = "/se-loger/tous-les-programmes-immobiliers-neufs/"
to = "/informations-pratiques/tous-les-programmes-immobiliers-neufs/"
status = 301

[[redirects]]
from = "/urbanisme/regles-durbanisme-a-la-parcelle-nru/"
to = "/informations-pratiques/regles-durbanisme-a-la-parcelle-nru/"
status = 301

[[redirects]]
from = "/equipe/"
to = "/"
status = 301

[[redirects]]
from = "/se-loger/sabonner-a-leau-potable/"
to = "/informations-pratiques/sabonner-a-leau-potable/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/consulter-les-documents-du-plui/"
to = "/informations-pratiques/consulter-les-documents-du-plui/"
status = 301

[[redirects]]
from = "/actualites/famille-2/caterogie-2/"
to = "/famille-2/caterogie-2/"
status = 301

[[redirects]]
from = "/actualites/"
to = "/"
status = 301

[[redirects]]
from = "/organisations/accueil-de-loisirs-dominique-savio/"
to = "/"
status = 301

[[redirects]]
from = "/urbanisme/les-procedures-participatives-obligatoires-en-cours/"
to = "/informations-pratiques/les-procedures-participatives-obligatoires-en-cours/"
status = 301

[[redirects]]
from = "/agenda/public/enfant-et-familles/"
to = "/public/enfant-et-familles/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/habitat-participatif/"
to = "/informations-pratiques/habitat-participatif/"
status = 301

[[redirects]]
from = "/urbanisme/logements-degrades/"
to = "/informations-pratiques/logements-degrades/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/fabrique-citoyenne/"
to = "/informations-pratiques/fabrique-citoyenne/"
status = 301

[[redirects]]
from = "/urbanisme/construction-demolition-les-demarches-durbanisme/"
to = "/informations-pratiques/construction-demolition-les-demarches-durbanisme/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/le-reglement-local-de-publicite-intercommunal/"
to = "/informations-pratiques/le-reglement-local-de-publicite-intercommunal/"
status = 301

[[redirects]]
from = "/agenda/types-devenement/cinema-projection/"
to = "/types-devenement/cinema-projection/"
status = 301

[[redirects]]
from = "/actualites/famille-3/"
to = "/famille-3/"
status = 301

[[redirects]]
from = "/urbanisme/patrimoine-des-centres-anciens/"
to = "/informations-pratiques/patrimoine-des-centres-anciens/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/sabonner-a-leau-potable/"
to = "/informations-pratiques/sabonner-a-leau-potable/"
status = 301

[[redirects]]
from = "/informations-pratiques/projets-urbains/sabonner-a-la-newsletter-sur-les-projets-urbains/"
to = "/informations-pratiques/sabonner-a-la-newsletter-sur-les-projets-urbains/"
status = 301

[[redirects]]
from = "/agenda/archives/"
to = "/"
status = 301

[[redirects]]
from = "/ecole-maternelle-oscar-leroux/"
to = "/"
status = 301

[[redirects]]
from = "/se-loger/testez-votre-connexion-internet/"
to = "/informations-pratiques/testez-votre-connexion-internet/"
status = 301

[[redirects]]
from = "/agenda/2024/"
to = "/2024/"
status = 301

[[redirects]]
from = "/equipe/florian-guillanton/"
to = "/florian-guillanton/"
status = 301

[[redirects]]
from = "/organisations/categories/social-sante/"
to = "/social-sante/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/ecowatt-pour-veiller-sur-sa-consommation-electrique/"
to = "/informations-pratiques/ecowatt-pour-veiller-sur-sa-consommation-electrique/"
status = 301

[[redirects]]
from = "/categories/culture-loisirs/"
to = "/culture-loisirs/"
status = 301

[[redirects]]
from = "/agenda/public/"
to = "/public/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/construction-demolition-les-demarches-durbanisme/"
to = "/informations-pratiques/construction-demolition-les-demarches-durbanisme/"
status = 301

[[redirects]]
from = "/actualites/caterogie-2/"
to = "/famille-2/caterogie-2/"
status = 301

[[redirects]]
from = "/accueil-de-loisirs-dominique-savio/"
to = "/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/ecotravo-vous-aide-a-renover-votre-logement/"
to = "/informations-pratiques/ecotravo-vous-aide-a-renover-votre-logement/"
status = 301

[[redirects]]
from = "/organisations/categories/education/"
to = "/education/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/mieux-comprendre-le-plui-questions-et-reponses/"
to = "/informations-pratiques/mieux-comprendre-le-plui-questions-et-reponses/"
status = 301

[[redirects]]
from = "/agenda/types-devenement/"
to = "/types-devenement/"
status = 301

[[redirects]]
from = "/se-loger/habitat-participatif/"
to = "/informations-pratiques/habitat-participatif/"
status = 301

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/"
status = 301

[[redirects]]
from = "/projets-urbains/sabonner-a-la-newsletter-sur-les-projets-urbains/"
to = "/informations-pratiques/sabonner-a-la-newsletter-sur-les-projets-urbains/"
status = 301

[[redirects]]
from = "/se-loger/les-aides-a-lachat-dun-logement/"
to = "/informations-pratiques/les-aides-a-lachat-dun-logement/"
status = 301

[[redirects]]
from = "/se-loger/logement-pour-les-jeunes-et-les-etudiants/"
to = "/informations-pratiques/logement-pour-les-jeunes-et-les-etudiants/"
status = 301

[[redirects]]
from = "/categories/education/"
to = "/education/"
status = 301

[[redirects]]
from = "/agenda/quartiers/"
to = "/quartiers/"
status = 301

[[redirects]]
from = "/agenda/2024/10/"
to = "/2024/10/"
status = 301

[[redirects]]
from = "/organisations/categories/culture-loisirs/"
to = "/culture-loisirs/"
status = 301

[[redirects]]
from = "/organisations/association-des-bibliotheques-et-sonotheques-en-etablissements-hospitaliers-de-rennes-et-sa-region/"
to = "/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/les-procedures-participatives-obligatoires-en-cours/"
to = "/informations-pratiques/les-procedures-participatives-obligatoires-en-cours/"
status = 301

[[redirects]]
from = "/equipe/elisabeth-feuillebois/"
to = "/elisabeth-feuillebois/"
status = 301

[[redirects]]
from = "/informations-pratiques/projets-urbains/nouvelles-fabriques-de-la-ville/"
to = "/informations-pratiques/nouvelles-fabriques-de-la-ville/"
status = 301

[[redirects]]
from = "/agenda/"
to = "/"
status = 301

[[redirects]]
from = "/projets-urbains/a-voir-pour-integrer-des-acces-directs-vers-les-sites-de-projets-urbains-sites-territoires/"
to = "/informations-pratiques/a-voir-pour-integrer-des-acces-directs-vers-les-sites-de-projets-urbains-sites-territoires/"
status = 301

[[redirects]]
from = "/urbanisme/le-reglement-local-de-publicite-intercommunal/"
to = "/informations-pratiques/le-reglement-local-de-publicite-intercommunal/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/droits-de-preemption/"
to = "/informations-pratiques/droits-de-preemption/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/se-loger-a-rennes-quand-on-vieillit/"
to = "/informations-pratiques/se-loger-a-rennes-quand-on-vieillit/"
status = 301

[[redirects]]
from = "/organisations/mairie-de-bourgbarre/"
to = "/"
status = 301

[[redirects]]
from = "/urbanisme/fabrique-citoyenne/"
to = "/informations-pratiques/fabrique-citoyenne/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/les-procedures-participatives-obligatoires-archivees/"
to = "/informations-pratiques/les-procedures-participatives-obligatoires-archivees/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/referentiel-bas-carbone-mode-demploi/"
to = "/informations-pratiques/referentiel-bas-carbone-mode-demploi/"
status = 301

[[redirects]]
from = "/organisations/4bis-information-jeunesse/"
to = "/4bis-information-jeunesse/"
status = 301

[[redirects]]
from = "/informations-pratiques/se-loger/testez-votre-connexion-internet/"
to = "/informations-pratiques/testez-votre-connexion-internet/"
status = 301

[[redirects]]
from = "/association-des-bibliotheques-et-sonotheques-en-etablissements-hospitaliers-de-rennes-et-sa-region/"
to = "/"
status = 301

[[redirects]]
from = "/actualites/2025-09-23-actualite-pour-latelier-au-festival-de-linfo-locale/"
to = "/2025-09-23-actualite-pour-latelier-au-festival-de-linfo-locale/"
status = 301

[[redirects]]
from = "/informations-pratiques/projets-urbains/a-voir-pour-integrer-des-acces-directs-vers-les-sites-de-projets-urbains-sites-territoires/"
to = "/informations-pratiques/a-voir-pour-integrer-des-acces-directs-vers-les-sites-de-projets-urbains-sites-territoires/"
status = 301

[[redirects]]
from = "/categories/mairies/"
to = "/mairies/"
status = 301

[[redirects]]
from = "/urbanisme/mieux-comprendre-le-plui-questions-et-reponses/"
to = "/informations-pratiques/mieux-comprendre-le-plui-questions-et-reponses/"
status = 301

[[redirects]]
from = "/informations-pratiques/urbanisme/regles-durbanisme-a-la-parcelle-nru/"
to = "/informations-pratiques/regles-durbanisme-a-la-parcelle-nru/"
status = 301

[[redirects]]
from = "/se-loger/referentiel-bas-carbone-mode-demploi/"
to = "/informations-pratiques/referentiel-bas-carbone-mode-demploi/"
status = 301

[[redirects]]
from = "/actualites/famille-1/categorie-1/"
to = "/famille-1/categorie-1/"
status = 301

